vanshchauhan21/CryptoTracker

- CODE_OF_CONDUCT.md
closes #1 
This is a PR raised to create a code of conduct markdown file for the CryptoTracker Repo as a part of WOB24 contributions. I have used the general template for reference and modified it based on the project/repo information. Email ID of the author of the project has been added for reporting purposes as a part of code of conduct regulations. Please review the PR and share the feedback. Also request to add wob24 label. Thank you for your review.
> #Add Code of Conduct #1

- src/components/LandingPage/MainComponent/styles.css
issue #85  fixed
This pull request addresses the issue of the unbalanced iPhone image when viewed in Android mode. The image has been adjusted for proper alignment and scaling to ensure a consistent and visually appealing appearance across all devices.
> Correct image alignment

- .env.sample
- package-lock.json
- package.json
- src/components/Common/Header/index.js
- src/index.js
- src/pages/Login.js
- src/pages/Signup.js
Issue: #89
We would like to implement Social Authentication in the CryptoTracker application, allowing users to sign up and log in using their existing Google or GitHub accounts (and potentially other providers). This will enhance user experience by simplifying the registration and login processes.
**Screenshots:**
before authenticating:
signup page:
login page:
after authenticating:
**Please label under GSSoC'24 ext and hacktoberfest labels**
> Feature Request: Add Authentication Using Google/GitHub etc

- src/components/Dashboard/List/styles.css
Realted issue : 
Fixes : #157 
Description : 
1) The list view under dashboard when hovered creates a kind of glitch which seems like the border is expanding in size a bit after a sec and that appears non-smooth unlike in grid section.
Solution : Added border of 2px soild var(--darkgrey)
Before : 
https://github.com/user-attachments/assets/dfa7722f-dcbb-4a15-bc37-94ed1b22f800
After : 
https://github.com/user-attachments/assets/2af6c785-258a-4945-a50d-0ee5b95d0f7a
2) Also, there is unevenness in UI of both grid and list making it non-consistent (like no background color in list in both light and dark mode)
Solution : Added background-color as var(--darkgrey)
Before : 
After :
> fixed list glitch and added background color

- src/components/Dashboard/Pagination/index.js
- src/components/Dashboard/Pagination/styles.css
Fixes : #155 
Description : 
Page no. text in dashboard was not clearly visible in light theme. I added some custom CSS to specifically handle Pagination title under both the themes.
Screenshots : 
Before : 
After :
> fixed pagination color in both the themes

- src/components/LandingPage/MainComponent/styles.css
#169 solved
The hero section and footer are currently overlapping, resulting in a cluttered appearance that disrupts the layout flow and user experience. This fix ensures proper spacing and alignment between the hero section and footer, preventing overlap and maintaining a clean, organized look across the page.
> Fix hero section and footer overlapping issue

- src/components/LandingPage/MainComponent/styles.css
fixed #192 
please add label level 3 if possible 
This PR addresses a readability issue on the home page in Dark Mode, where the "Real Time" text was difficult to see due to low contrast with the background. The color has been adjusted to ensure sufficient contrast, improving text visibility and enhancing user experience across display modes.
> Improve "Real Time" text visibility in Dark Mode

- src/pages/Privacy-Policy/PrivacyPolicy.css
fixed #203 
This update brings dark mode support to the Privacy Policy page, enhancing user experience for those browsing in low-light conditions. The theme toggle seamlessly adapts the page’s appearance to align with the rest of the site’s dark mode styling, improving readability and comfort.
https://github.com/user-attachments/assets/308fc5a6-7851-42bc-9102-21cc1aceead9
> Improved  darkmode on privacypolicy page

- src/components/Footer.jsx
Related issue
Fixed #212 
Description : 
Added copyright for CryptoTracker in the footer section
Screenshot : 
Before : 
After : 
Please review my PR and label it under WoB, GSSoC and Hacktoberfest
> added copyright claims

- src/pages/Pricing/Pricing.css
Related issue 
Fixed #240 
Description : 
Added dark mode theme for pricing section using custom CSS for different themes
Screenshots : 
Before : 
After :
> added dark mode support for pricing section

- src/pages/Login.js
- src/pages/Signup.js
Fixed #272 
---
The Sign up link in "doesn't have an account" redirects by default to [accounts.dev/sign-up](https://noted-terrier-69.accounts.dev/sign-up) whereas it should redirect to [/signup](https://crypto-tracker-kappa-ebon.vercel.app/signup) .The same goes for login link in signup page.
---
Irtesaam Atfi
---
irtesaam
---
GSSoC
WoB
Hacktoberfest
---
Closes: #272 
---
The problem lies in the default URL set by Clerk authenticator used in the website.
So I overwrite those default URLs using Javascript appearance and href keys and pointed the new link to the /signup and /login page which are already present in the codebase.
Also , I have used custom CSS properties to position the new texts and link at the correct location on the login and signup page.
---
---
Notice the page URLs …
> fixed clerk authenticator default URL problem

- src/components/LandingPage/MainComponent/styles.css
Fixed #274 
---
"Real Time" is not visible in dark mode because a CSS property with high precedence was overwriting the default one.
---
GSSoC
WoB
Hacktoberfest
---
Closes  #274 
---
Removed the contradicting CSS property color: var(--black) !important; and added a var(--heading1-color) which will adjust as per theme
---
---
Before : 
https://github.com/user-attachments/assets/32db1ccb-d4ca-4746-8494-745fa224f4c9
After : 
https://github.com/user-attachments/assets/005932c8-c46c-41e0-888c-11e8d2af672c
---
> fixed heading text blending in dark mode

- src/pages/Marquee/Marquee.css
Fixed #276 
---
As in the screenshot below, when marquee content is clicked through logo, it points to the page which came previous whereas if clicked on the text, then it points to the right page. This bug is likely due to some overlap between previous content's text and next content's logo.
---
Irtesaam
---
irtesaam
---
GSSoC
WoB
Hacktoberfest
---
*Closes: #276 *
---
1) Fixed overlapping of logos and text to avoid clicking on previous link
2) Changed flex-direction from row to column for logo-box which gives much cleaner look.
---
---
Notice the page it opens when clicked on logo and text in before and after.
Before : 
https://github.com/user-attachments/assets/1464975d-e520-466c-9948-7af578f45d4a
After : …
> fixed marquee contents links and appearance

- src/pages/CryptoConverter.css
fixed #267 
1. Addressed visibility issue in the crypto converter by improving text and background contrast in dark mode.
2. Adjusted color scheme to ensure clear readability, enhancing user experience and usability when dark mode is enabled.
3. This update ensures that content is fully visible and accessible, aligning with the dark theme across the site.
> Enhance Contrast for Crypto Converter in Dark Mode

- src/components/GoogleTranslate.jsx
fixed #249
Updated the text and border color of the "Select Language" component to align with the footer's theme, ensuring a cohesive and visually appealing design.
This change improves the footer's aesthetic consistency, particularly in dark mode and other themed views, making the language selection component more readable.
> "Updated styles for Google Translate component"

- src/components/Footer/Footer.jsx
- src/index.css
Fix background color mismatch for GitHub and Visitor Count frames to match footer
---
The GitHub and Visitor Count frames currently have a background color that doesn’t match the footer’s background, creating an inconsistent visual appearance. This update aligns the background color of these frames with the footer's color scheme to ensure a cohesive look across all page elements. Matching the colors will improve the page's visual flow, enhancing user experience with a uniform design.
---
*Closes: #360*
---
> Fix background color mismatch for GitHub and Visitor Count frames to match footer

- src/pages/CryptoProfitCalculator.js
Fixed #329 
---
There was no dark mode theme available for Crypto Profit calculator
---
Irtesaam
---
irtesaam
---
GSSoC
WoB
Hacktoberfest
---
*Closes: #329 *
---
integrated dark mode theme in crypto profit calculator using Tailwind predefined classes for dark themes.
---
---
Before : 
https://github.com/user-attachments/assets/0dc562ff-c6b7-4b64-a978-502ec560ebfb
After : 
https://github.com/user-attachments/assets/32db9b59-6ba8-48a6-83c8-31d38c23913b
---
> integrated dark mode theme in crypto profit calculator

- src/pages/ImpermanentLossCalculator.css
fixed #349 
The content of Impermanent Loss Calculator is now visible in dark mode
> Content visibility in dark mode 

- src/pages/WhatsTrending/WhatsTrending.js
This PR adds a Navbar and Footer to the "What’s Trending" route, along with CSS for dark mode compatibility, enhancing the page structure and user experience.
@vanshchauhan21 
'fixed #447 '
> Add Navbar, Footer, and Dark Mode Support to What’s Trending Route

- src/pages/ProfitLoss/ProfitLoss.css
#546  Fixed
Addressed a severe content visibility issue on the Portfolio Profit and Loss page, where crucial information was unreadable in both dark and light modes. Adjustments were made to the color scheme and contrast to ensure that all data is clearly visible regardless of the selected theme. This fix enhances usability and provides a consistent viewing experience across display modes.
https://github.com/user-attachments/assets/15379a41-27e8-45d9-8e1f-8e877ae0a8eb
> Fix content visibility on Portfolio Profit and Loss page

- src/pages/Contributors.css
- src/pages/Contributors.js
This PR centers the Lottie spinner on the Contributors page to improve the user experience during asynchronous data loading. It also ensures that the layout of the Contributors page is optimized for better visual alignment.
'fixed #574 '
https://github.com/user-attachments/assets/a0e71b80-d239-41e0-9ff9-ef686a0e59be
> Implement Centered Lottie Spinner in Contributors Page

- src/components/Feedback/Feedbacksection.css
- src/components/News.jsx
Issue Title
[Frontend issue] Unreadable text in News section during dark mode
Info about the Related Issue
What's the goal of the project?
To create a responsive and visually accessible crypto tracking application that works seamlessly across light and dark themes.
Name
Abhishek Singh
GitHub ID
@Abhishek-singh88
Identify Yourself
SSOC S4 Participant
Closes
Closes: #919 
Describe the Add-ons or Changes You've Made
Fixed the issue where the News section text (“Sorry, No Items In The News.”) was unreadable in dark mode.
Added Tailwind’s dark:text-white utility to ensure text remains visible on dark backgrounds.
Also removed 3 extra closing braces from `src/components/Feedback/Feedbacksection.css
` that were causing a build failure, though unrelated to the main issue.
Type of Change
Bug fix …
> fix: Make News section text readable in dark mode

- .stylelintrc.json
- index.html
- package-lock.json
- package.json
- public/index.html
- src/App.js
- src/components/Chatbot-button/Chatbot.css
- src/components/Chatbot-button/Chatbot.js
- src/components/Feedback/Feedbacksection.css
- src/index.css
**Added Chatbot Feature and Fixed an earlier tailwind CSS error**  
- [✅] I have provided the issue title.
---
*Adding a chatbot button on the right side present on all places for easy access by the user.*
- [✅ ] I have described the aim of the project.
---
*Beas Jana*
- [✅ ] I have provided my name.
---
*bwbeas*
- [✅ ] I have provided my GitHub ID.
---
*SSOC Contributor*
- [ ✅] I have mentioned my participant role.
---
*Closes: #916 *
- [ ✅] I have provided the issue number.
---
**Give a clear description of what you have added …
> Added Chatbot Feature and Fixed an earlier tailwind CSS error
