netlify.toml
package-lock.json

Adding some minor changes for calculation ease.

CryptoTracker

---

package-lock.json
src/components/Common/Button/styles.css
src/components/Common/Header/index.js
src/components/Common/Header/styles.css

**Pull Request: Enhance Navbar Hover Effect and Button Styling**
- Fixes issue #4 
-  Fixes issue  #6 
**Changes Made:**
**Let me know if any other touch are needed! Thank you 👍**
Ping @vanshchauhan21

Some front-end touch done

---

src/components/CoinPage/SelectDays/index.js
src/components/CoinPage/SelectDays/styles.css
src/components/CoinPage/ToggleComponent/index.js

Adjusted dark theme for better visibility and experience in dark mode
fixes #19 
here is a demo after the changes:
https://github.com/user-attachments/assets/738019a6-9eb8-45b0-84a3-919c1af415a9

Adjust toggle, table for dark theme

---

package-lock.json
package.json
src/components/Common/Header/index.js

Remove alert message

---

README.md

Dear @vanshchauhan21,
I have completed the contributing guide as previously discussed. Please find the key enhancements made to the project documentation:
1.Enhanced Project Description.
2.Listed the application features for easy reference.
3.Specified the technologies used in the project.
4.Added step-by-step installation guidance for new users.
5.Clear steps for Contributing Section.
6.Added a light-hearted ending to engage readers.
Please merge these changes into the main branch.
I’d also appreciate being assigned to GSSOC-Ext and Hacktoberfest.
Thank you!
Best regards,
Ishrat noori :)

Updated README with project details

---

src/App.css
src/App.js
src/index.css

@vanshchauhan21, i updated meta color , merge it and close the issue #26

update footer meta color

---

src/components/Common/Header/drawer.js
src/components/Common/Header/index.js

#15 Issue Fixed
Anchor tag for logo, removed home tab

Anchor tag for logo

---

package-lock.json
package.json
src/components/Common/Header/index.js
src/components/Common/Header/styles.css

I have fixed the following:-
1. Redesign the Navbar.
2. Enhance the Styling of the navbar.
3. Enhance the Theme Toggling.
4. Make Proper Responsiveness.
5. Added Border styling on the navbar to differentiate it from the main content/body.
https://github.com/user-attachments/assets/5ce0b424-3b0e-4640-8fa0-23c3efe55ce8
https://github.com/user-attachments/assets/a9b3c59c-0ec8-49e2-a31b-b174399c7d40
Completed #13

Enhance Navbar | Issue #13

---

public/index.html
src/components/ComparePage/SelectCoins/styles.css
src/components/Footer.jsx

Added icons and removed text for social media

---

Contributing.md

@vansh
#42 completed
please add lable it too.

contributing.md file added

---

src/components/Common/Footer/styles.css

change the footer style (resolve issue #53)
before 
after------
**pls merge this pr ASAP!!!**

fix the footer(copywrite)(issue#53)

---

src/App.css
src/App.js
src/components/Footer.jsx
src/pages/TermCondition.js

This pull request adds a "Terms and Conditions" link to the footer of the Crypto Tracker application. This addition helps improve compliance and user awareness regarding the terms of use for the application.
- Updated the `Footer.jsx` component to include a new link titled "Terms and Conditions".
- Ensured that the link is styled consistently with existing footer elements.
- Added routing for the link to point to the corresponding Terms and Conditions page (if applicable).
Including a "Terms and Conditions" link is essential for informing users about the policies governing the use of the application. This change aligns with best practices for transparency and user experience.
- Review the implementation for any feedback.
- Test the link to ensure it directs to the correct page.
[Add any …

Add Terms and Conditions Link to Footer

---

src/App.css
src/App.js
src/components/Footer.jsx
src/pages/PrivacyPolicy.js

This pull request implements a dedicated Privacy Policy page for the Crypto Tracker application. The page outlines our data practices and aims to enhance transparency with users regarding their privacy.
- Created a new `PrivacyPolicy.jsx` component that contains the structure for the Privacy Policy.
- Added a link to the Privacy Policy in the footer of the application.
While the basic structure of the Privacy Policy page has been established, I currently have placeholder text. I will update the content once I receive further information regarding our specific privacy practices and policies.
Please provide the details necessary to complete the Privacy Policy so that I can fill in the relevant information and ensure compliance with privacy standards.
fixed : #46 …

Add Privacy Policy page and link in footer

---

src/components/LandingPage/MainComponent/styles.css

fix image overlap on home screen

---

src/App.css
src/index.css

Added hover effect in footer- Quick links and icons

---

src/App.js
src/pages/Dashboard.js

issue #67 solved 
Removed the redundant footer by ensuring only one instance is rendered on the dashboard.

Corrected duplicate footer

---

package-lock.json
src/App.js
src/components/Common/Header/drawer.js
src/components/Common/Header/index.js
src/components/Footer.jsx
src/index.css
src/pages/Faq.js
src/pages/Login.js
src/pages/Signup.js

FIXES: #62 
both pages are responsive , fully functional with eye hide/show option also. After successful login, user will automatically redirect to the home page.

Feature authentication with login and sign up page done.

---

src/App.js
src/components/Footer.jsx
src/index.css
src/pages/Faq.js

responsive faq section added

---

package-lock.json
src/App.js
src/components/Common/Header/drawer.js
src/components/Common/Header/index.js
src/components/Footer.jsx
src/index.css
src/pages/Faq.js
src/pages/Login.js
src/pages/Signup.js
src/pages/Watchlist.js

FIXES: #64 
https://github.com/user-attachments/assets/f47db5de-3b5f-428e-80c6-c7d0b71b9414

Feature watchlist text appears in dark/light mode.

---

public/index.html

Integrated a chatbot that provides instant answers to user inquiries. The chatbot is site specific and answers queries related to the website or general queries
closes #72 
https://github.com/user-attachments/assets/688a2934-7cba-454c-ae9a-4b079e3d34ec

added chatbot for enhanced user experience

---

.env
src/App.js
src/components/CoinPage/LineChart/index.js
src/components/CoinPage/SelectDays/index.js
src/components/CoinPage/ToggleComponent/index.js
src/components/ComparePage/SelectCoins/index.js
src/components/Dashboard/Grid/index.js
src/components/Dashboard/List/index.js
src/components/Dashboard/Pagination/index.js
src/components/Dashboard/Search/index.js
src/components/Dashboard/Tabs/index.js
src/components/LandingPage/MainComponent/index.js
src/functions/convertNumber.js
src/functions/getPrices.js
src/functions/removeItemToWatchlist.js
src/pages/Dashboard.js
src/pages/Faq.js

Fixed: #102
just merge it and again  i am going to make another feature @vanshchauhan21

add header in the FAQ page

---

.github/workflows/issue_close_open.yml
.github/workflows/pr_merge.yaml
.github/workflows/pr_raise.yml

implemented github workflows for the following things:
Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !
fixes #124 
close #124 
add level2 or level 3 label

🚀 Automate Connections with GitHub Actions!

---

.github/workflows/pr-checker.yml

Description:
This workflow automatically runs checks on every pull request. It ensures that PRs meet basic criteria, such as:
issue #127 
close #127 
1. Checking for a descriptive title and body.
2. Running linting and basic tests to validate code quality.
3. This helps maintain PR quality and catch issues early in the review process.

Created pr-checker.yml

---

src/pages/Dashboard.js

issue #130 fixed
I have removed the duplicate footer  that was appearing on the dashboard page 
https://github.com/user-attachments/assets/79f802da-64be-4695-bb3f-bb38b5d9c9f7

Remove duplicate footer

---

package-lock.json
package.json
src/pages/Login.js
src/pages/Signup.js

#99 Solved
A home icon has been added to the login and sign-up pages, enhancing user navigation by providing a clear and consistent way to return to the home page. This addition aligns with the design used on other pages, improving the overall user experience and ensuring consistent navigation options across the site.
https://github.com/user-attachments/assets/7fe17c3f-08e2-40e6-b58a-7dd1f4a300cd

Add Home Icon on Login and Sign-Up Pages

---

src/App.css
src/App.js
src/components/Common/Contributors Card/ContributorCard.css
src/components/Common/Contributors Card/ContributorCard.js
src/components/Footer.jsx
src/locales/en.json
src/locales/es.json
src/locales/zh.json
src/pages/Contributors.js
src/pages/Dashboard.js

- Created ContributorCard component with CSS for displaying contributor profiles.
- Updated App.js and Dashboard.js to integrate the new Contributors page.
- Added English, Spanish, and Chinese translations in en.json, es.json, and zh.json.
- Modified Footer component to reflect changes.
Fixed:#113
@vanshchauhan21 
https://github.com/user-attachments/assets/074c0027-2905-4654-aaf9-697f30dadbd0

Add Contributors Card Component and Multi-language Support

---

src/components/Common/Footer/styles.css

issue #129 fixed 
I have changed the gradient of the footer so that it matches with the header logo
https://github.com/user-attachments/assets/6af60990-18f6-4bd4-93c2-7dee2fb33a4c

change footer gradient

---

src/components/LandingPage/MainComponent/index.js
src/components/LandingPage/MainComponent/styles.css

Fixes : #162 
Description : 
The share app dialog box was not styled properly. The key features at which I worked to improve its appearance are as follows : 
1) Centered the dialog box on the page rather than positioning it at the bottom.
2) Reduced dialog container size for a more natural look.
3) Enabled color adaptation in dark mode.
4) Added a darker background behind the dialog box to draw focus.
5) Applied a matching border radius at the bottom, consistent with the top.
Before : 
After : 
Please review my PR and label it under GSSoC, WoB and Hacktoberfest.

improved Share App dialog box using custom CSS

---

src/components/Common/Header/index.js
src/components/Common/Header/styles.css

#142 fixed
This update introduces an active link highlight feature within the navbar, allowing users to easily identify their current page. Each time a page is selected, the corresponding navbar button will be highlighted, enhancing navigation clarity and improving overall user experience.
https://github.com/user-attachments/assets/d97198d9-206f-49b7-aea1-c73631870d53

Fix - Implement active link highlight in navbar for improved navigation

---

src/components/Common/Footer/styles.css
src/components/LandingPage/MainComponent/index.js
src/components/LandingPage/MainComponent/styles.css

issue #123 solved
Resolved an issue where the shadow effect on the iPhone image was overlapping with footer , causing visual inconsistency. Adjusted some properties to ensure it remains well-defined without interference, enhancing the layout's readability and aesthetic appeal.
https://github.com/user-attachments/assets/0b3b0037-6bb6-453a-9cd6-ad86f06be516

Resolved shadow overlapping

---

src/App.css
src/components/Common/Footer/styles.css

This pull request addresses the layout issues observed in the Footer section when viewed on Android devices. The previous implementation resulted in an oversized footer with excessive spacing between the headlines, negatively impacting the overall user experience and aesthetic appeal.
https://github.com/user-attachments/assets/97dd154e-b1e6-430f-9efd-f1ffb7642547

Improve Footer Responsiveness on Android Devices

---

src/components/Dashboard/Tabs/index.js
src/components/Dashboard/Tabs/styles.css
src/components/LandingPage/MainComponent/styles.css

issue #159 fixed
I have updated the color of grid and list according to light and dark mode 
In light mode:
In dark mode:

update grid list color

---

src/components/Common/Header/drawer.js
src/components/Common/Header/index.js
src/components/LandingPage/MainComponent/styles.css

#161 fixed
The Home button is currently missing in the mobile version of the navbar, affecting the navigation experience for users on smaller devices. This update includes the addition of a Home button to the navbar for mobile views, ensuring a consistent navigation experience across all devices.

Fix -  Home Button Missing in Navbar on Mobile Devices

---

package-lock.json
package.json
postcss.config.js
src/index.css
src/pages/TermCondition.js
tailwind.config.js

**feat: Add Terms and Conditions page for Crypto Tracker Platform**
This PR introduces a new **Terms and Conditions** page to the Crypto Tracker platform. Below are the details of the implementation:
- Added a dedicated Terms and Conditions page with key sections:
- **Introduction**
- **User Accounts**
- **Data Privacy**
- **Disclaimer**
- **Contact Information**
- The page is built using **React** and styled with **Tailwind CSS** for responsiveness and a clean UI.
- Integrated responsive design for a seamless user experience on both mobile and desktop screens.
_Provide screenshots to give reviewers a quick visual overview of the page._
Before
After
To provide a more interactive overview, a video has been included showing:
- Navigation to the Terms and Conditions page.
- Responsive …

Feat: Added TermCondition Page

---

src/components/Common/Contributors Card/ContributorCard.css
src/pages/Contributors.css
src/pages/Contributors.js

fixed #166 
This update addresses the visual inconsistency of contributor cards on the Contributors page by redesigning them to align with the project's overall theme. The new design ensures a cohesive user experience, enhancing visual harmony across the application. The contributor cards now reflect the branding and aesthetic principles established in other sections, improving both usability and visual appeal. This change contributes to a more unified and polished interface.
https://github.com/user-attachments/assets/a1007da5-67a6-45f5-a194-01a3bc3dbe99

Redesign Contributor Card to Align with Project Theme

---

src/components/Dashboard/Search/styles.css

- fixed #168 
- Adds proper spacing between navbar and search component

Add spacing between navbar and search box on dashboard

---

src/components/Common/Price Card/PriceCard.css

fixed #177  
I have adjusted the colors of the pricing cards to match with the website theme  also added some transitions on them

Adjusted color of pricing cards

---

src/App.js
src/components/Common/Header/drawer.js
src/components/Common/Header/index.js
src/components/Learn.jsx

fixes #108 
@vanshchauhan21 please review this pr thanks!

added Learn Section

---

src/App.js
src/components/Common/Header/drawer.js
src/components/Common/Header/index.js
src/components/InputBox.jsx
src/components/LandingPage/MainComponent/CurrencyConvertor.jsx
src/components/LandingPage/MainComponent/index.js
src/components/index.js
src/hooks/useCurrencyInfo.js

fixes #109 
@vanshchauhan21 please review this pr thanks

added currency convertor

---

src/App.css

Realted issue : 
Fixed #179 
Description : 
Fixed broken theme in dark mode. Only navbar was changing according to the theme. Now the page's body also changes.
Screenshots : 
Before : 
After :

fixed broken theme in dark mode

---

src/components/LandingPage/MainComponent/styles.css

fixed #176 
This update resolves the color inconsistency of the subscribe button in the footer section. Previously, the button color did not adapt seamlessly with the theme, unlike the language selection box, resulting in a disjointed appearance. With this correction, the subscribe button now aligns with the theme, ensuring a cohesive and visually harmonious footer design that enhances the overall aesthetic of the page.
https://github.com/user-attachments/assets/a7b796de-f971-489a-8c84-3173483531b1

Aligned Subscribe Button Color with Footer Design

---

src/pages/Contributors.css
src/pages/Contributors.js

Closes : #117
https://github.com/user-attachments/assets/712c7df2-2079-4eef-91a4-6aa658b64a90

Added contributor's page

---

src/App.js
src/components/Common/ProgressBar/ProgressBar.css
src/components/Common/ProgressBar/ProgressBar.js

fixed #196 
This PR introduces a progress bar to the website to improve navigation and user experience. The progress bar visually represents the user’s scroll progress on each page, providing feedback on their position within the content. This feature makes it easier for users to navigate lengthy pages and enhances overall usability.
https://github.com/user-attachments/assets/66d0048e-5617-499e-9632-3557ba7c9d4a

Add Progress Bar for Enhanced Navigation

---

src/App.js
src/components/Footer.jsx
src/pages/Disclaimer/Disclaimer.css
src/pages/Disclaimer/Disclaimer.js

This PR adds a new Disclaimer page to the Crypto Tracker application, ensuring users can access legal information about the platform.
Changes Implemented:
App.js
Added a new route for the Disclaimer page.
Footer.jsx
Updated the footer to include a link to the Disclaimer page.
Disclaimer Page (New)
Created a dedicated Disclaimer page with relevant content and styling.
The page provides general information about Crypto Tracker's liability and terms of use.
'fixed:#151' @vanshchauhan21 
https://github.com/user-attachments/assets/177c7735-35f4-4bed-8977-693ae84916d8

Feature/Add Disclaimer Page with Route and Footer Link

---

src/App.js
src/components/Footer.jsx
src/components/GoogleTranslate.jsx
src/pages/Contributors.js

Closes: #115 
https://github.com/user-attachments/assets/4460e877-8e65-47b5-8fcb-df1484fcb2aa

Multi-Language Support Using Language Translator

---

src/components/Learn.css
src/components/Learn.jsx

fixed #199 
The Learn page now includes a dark mode option to enhance readability and reduce eye strain in low-light environments. With a simple toggle, users can switch between light and dark themes, allowing for a more personalized and comfortable learning experience.

Added darkmode on learn page

---

src/components/Learn.jsx

Related issue 
Fixed #221 
Description : 
1) Added more readings in the learn cryptocurrency page
2) Added links to that readings (usually medium.com)
Screenshots : 
Before : 
https://github.com/user-attachments/assets/0eaf292f-b7d8-4d00-b675-fd5e84f7a4d4
After : 
https://github.com/user-attachments/assets/f0e48a70-958f-442d-a387-0014f983be46
Please review my PR and label it under GSSoC, WoB and Hacktoberfest

added more readings and links for learn cryptocurrency page

---

src/App.js
src/components/Footer.jsx
src/pages/Cookie-Policy/CookiePolicy.css
src/pages/Cookie-Policy/CookiePolicy.js

This pull request introduces a new Cookie Privacy Policy page to the CryptoTracker application. The following changes have been made:
New Page: Created a dedicated Cookie Policy page with comprehensive information about how cookies are used on the platform, including details on user consent and cookie management.
Routing: Updated the App component to include routing for the Cookie Policy page, making it accessible from the main application.
Footer Update: Modified the Footer component to include a link to the new Cookie Policy page for easy access.
Styling: Added styling for the Cookie Policy page to ensure consistency with the existing design of the application.
'fixed:#202'  @vanshchauhan21 
https://github.com/user-attachments/assets/7beceed1-1dbe-4161-846b-309c7ca36e88

Feature: Implement Cookie Privacy Policy Page

---

src/index.css
src/pages/Login.js
src/pages/Signup.js

Fixed #218 
Description : 
The dark mode feature for the login and signup pages now automatically detects theme changes and updates the UI to match the selected mode. When the theme is switched to dark mode, both pages adapt seamlessly to reflect the change.
Screenshots : 
Before : 
https://github.com/user-attachments/assets/5776b8fc-5118-4cbd-9db9-c0236795d887
After : 
https://github.com/user-attachments/assets/d9368523-87ea-45e3-941d-2065d14f554d
Please review my PR and label it under GSSoC, WoB and Hacktoberfest

added dark mode features to login and signup page

---

src/pages/Privacy-Policy/PrivacyPolicy.css

Fixed #215 
Description : 
Fixed underline on card's text. Now its visible clearly without any underlines.
Screenshots : 
Before : 
After : 
Please review my PR and label it under GSSoC, WoB and Hacktoberfest.

fixed blue underlines in dashboard card's text

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/documentation-update.yml
.github/ISSUE_TEMPLATE/enhancement-request.yml

Add Bug Report, Enhancement Request, Documentation Update template
Issue - #208

Add Bug Report, Enhancement Request, Documentation Update template

---

src/App.js
src/components/Footer.jsx
src/pages/CryptoConverter.css
src/pages/CryptoConverter.js

Closes : #224 
https://github.com/user-attachments/assets/c62a5d1d-8219-4713-9f67-6c246be80b7e

Added Crypto Converter

---

.github/PULL_REQUEST_TEMPLATE.md

Add the PULL REQUEST TEMPLATE
Issue - #229

Add the PULL REQUEST TEMPLATE

---

src/components/LandingPage/MainComponent/index.js

Fixed #247 
---
Pricing appears on Home page whereas it should be on pricing page
---
Irtesaam Atfi
---
irtesaam
---
GSSoC
WoB
Hacktoberfest
---
*Closes: #247 
---
Removed the component from index.js which was rendering pricing section on home page
---
---
Before : 
After : 
---

fixed pricing appearing on home page

---

src/components/Common/Header/MobileMenuButton.css
src/components/Common/Header/MobileMenuButton.js
src/components/Common/Header/index.js
src/components/Common/Header/styles.css

fixed #186 
Corrected the navbar button display on mobile devices to improve navigation and accessibility, ensuring all options are easily accessible on smaller screens.
---
---
Priyanshi Bhargava
---
Priyanshi0112
---
GSS0C-ext
Contributor
---
Closes: #186
---
https://github.com/user-attachments/assets/fc944353-1b86-4212-9ea4-70ebac057895
---
---
---

Added mobile menu functionality to Header component

---

src/components/Common/Contributors Card/ContributorCard.css
src/pages/Contributors.css

Fixed #242 
---
Our contributors page's UI was almost broken and nothing was appearing on the screen clearly.
---
Irtesaam Atfi
---
irtesaam
---
GSSoC
WoB
Hacktoberfest
---
*Closes: #242 
---
I fixed the issue by : 
1) Adding some custom CSS to fix its styling
2) Adding smooth animations and page-consistent colors
3) Integrated the styling with both light and dark themes
4) Deleted some unused and repeated CSS styling
---
---
Before : 
https://github.com/user-attachments/assets/945b0d1d-57b5-44a4-96d9-7306b3e4023b
After : 
https://github.com/user-attachments/assets/187ff6ba-93e7-4bfe-b824-31e9f485e454
---

fixed our contrinutors page and improved its UI and animation

---

src/pages/Faq.js

Related issue
Fixed #236 
Description : 
Added more QnA in FAQs to improve user experience. This targets the common questions that arises in user's mind and hence aims to solve it.
Before : 
After : 
https://github.com/user-attachments/assets/53b25a88-01ee-4096-b299-0ad41244e363
Please review my PR and label it under GSSoC, WoB and Hacktoberfest.

added more QnA in FAQs to improve user experience

---

src/index.css

Fixed #230 
Screenshot : 
Before : 
https://github.com/user-attachments/assets/6327b365-2051-48a3-85a1-fa43721be9a3
After : 
https://github.com/user-attachments/assets/b4f51250-b9db-43f9-984e-e5ac3b840754

fixed text not visible in dark mode

---

src/pages/Feedback.js

#252 Fixed  
---
This update improves the feedback form's layout and user experience by aligning it with the site’s overall design, enhancing both usability and visual appeal. A consistent navbar is added to the feedback page, allowing users to navigate to other parts of the site easily. The design updates to the feedback form include improved spacing, updated color schemes, and better alignment, making it more engaging and accessible.
---
*Ritk Singh*
---
*ritiksingh-01*
---
*Gssoc - Extd : Contributor*
---
**Enter the issue …

 Enhance Feedback Form UI and Add Navbar

---

README.md

**📝[DOCS] adding Contributors section to readme.md**  
- [x ] I have provided the issue title.
---
to appreciate contributors
- [x ] I have described the aim of the project.
---
Amiya Singh
---
amiya-cyber
- [x ] I have provided my GitHub ID.
---
GSSOC,
Hactoberfest
- [ X] I have mentioned my participant role.
---
*Closes: #253 
fIXED #253 
- [x …

📝[DOCS] adding Contributors section to readme.md

---

src/App.css
src/pages/TermCondition.css
src/pages/TermCondition.js

In the dark mode content of terms and condition page is not visible 
---
In the dark mode content of terms and condition page  should be available
Resolved the visibility issue of content on the Terms and Conditions page in dark mode, ensuring text contrast is optimized for readability."
https://github.com/user-attachments/assets/229fd6e4-c282-4423-bcdb-3b369c69f95f
---
Priyanshi Bhargava
---
Priyanshi0112
---
GSSOC-ext : Contributor  
---
Closes: #250 
---
---
---
---

Updated Terms and Conditions page styling for dark mode

---

src/App.js
src/components/Footer.jsx
src/pages/CryptoProfitCalculator.css
src/pages/CryptoProfitCalculator.js

Added Crypto Profit Calculator
---
Tina Borundia
---
*Closes: #263
---
---
---
All [X]

Added Crypto Profit Calculator

---

src/App.js
src/components/Footer.jsx
src/pages/Useful Tools/ImpermanentLossCalculator.js

*Add Impermanent Loss Calculator Page to Improve User Access and Functionality*
---
*This update addresses the missing Impermanent Loss Calculator page, which is currently unavailable to users. Adding or restoring this page will allow users to calculate potential losses in liquidity pools, a crucial feature for those managing cryptocurrency assets. This change aims to enhance user experience by ensuring all necessary tools are accessible and functional, upholding the platform's value for crypto traders and investors.*
---
*Ritik Singh*
---
*ritiksingh-01*
---
**Mention in which program you are contributing (e.g., …

Add Impermanent Loss Calculator Page to Improve User Access and Functionality

---

src/App.css
src/components/Footer.jsx
src/components/GoogleTranslate.jsx

fixed #195 
1. Corrected the misalignment of the newsletter section in the footer to improve the visual consistency and layout across the website.
2. Adjusted styling to ensure the newsletter component aligns with other footer elements, enhancing overall readability and appearance.

fixed newsletter misalignment

---

README.md

Stargazers and Forkers section to readme.md
---
---
amiya singh
---
amiya-cyber
---
GSSOC
---
*Closes: #254 
- [x ] I have provided the issue number.
---
*Describe your …

Stargazers and Forkers section to readme.md

---

src/pages/Feedback.css
src/pages/Feedback.js

corrected feedback form title color

---

src/pages/Useful Tools/ProfitReturnCalculator.js

improve Profit Return Calculator input visibility in dark mode

---

src/pages/Marquee/Marquee.css

fixed #248 
This PR addresses the shadow styling of the logo in the footer to enhance visual consistency and clarity across themes

Corrected logo shadow in footer

---

src/components/Footer.jsx

Remove duplicate text  from useful tools in footer

---

src/App.css

*Footer is not responsive*
---
The goal is to fix the footer responsiveness.
---
Mohd Ahsan Raza Khan
---
*mohdahsanraazakhan*
---
*Hacktoberfest*
---
*Closes: #295*
---
I have added media query to make the footer responsive. 
---
---
Step 1: Go to the https://crypto-tracker-kappa-ebon.vercel.app/
Step 2: …

Fixed Footer Responsiveness

---

src/pages/BuyCryptoByCard/CardPurchaseLanding .js

---
---
---
---
---
---
---
---
--- …

added Buy Crypto with Card Compo

---

src/pages/CryptoConverter.css
src/pages/CryptoConverter.js

fixed #270 
https://github.com/user-attachments/assets/4d387a3d-b171-4d8b-826c-0c13bc7dd6c3

Added learn more section on cryptoconverter page

---

src/App.js
src/components/Footer.jsx
src/pages/CryptoMarket.css
src/pages/CryptoMarket.js

The component fetches data from the "CoinGecko API.
This API provides real-time cryptocurrency data, including prices, market caps, and 24-hour price changes.
Closes: #299
https://github.com/user-attachments/assets/bb51aeb7-b066-44a2-963d-82ac0247e9f2

Added Real-time cryptocurrency Market Data

---

package-lock.json
public/index.html

Enhance design of Back-to-Top button for improved user experience
---
The current Back-to-Top button design lacks visual appeal and can be improved for a better user experience. This PR updates the button style to make it more noticeable and user-friendly, including adjustments to color, icon design, and animations for smoother transitions. The improved design aligns with the overall aesthetic of the site, making the Back-to-Top button easy to spot and use, especially on pages with long scrolling. This enhancement aims to provide a more intuitive and visually pleasing navigation option for users.
---
Ritik Singh
---
ritiksingh-01
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, …

Enhance design of Back-to-Top button for improved user experience

---

src/components/CoinPage/Info/index.js
src/components/CoinPage/Info/styles.css
src/components/CoinPage/LineChart/index.js
src/components/CoinPage/ToggleComponent/index.js
src/pages/Coin.js

#307 Fixed
This PR introduces UI improvements across all Coin Pages to provide a more cohesive and user-friendly experience. Key changes include optimized layout, enhanced typography, consistent color schemes, and improved element alignment to ensure clarity and ease of navigation. These updates aim to make the Coin Pages more visually appealing and intuitive, aligning with the overall design language of the platform and ensuring a seamless experience for users exploring coin details.
https://github.com/user-attachments/assets/6571f332-1f7a-400a-a388-15403d6ff2c4

Improve UI design across all Coin Pages for enhanced user experienceImprove UI design across all Coin Pages for enhanced user experience

---

src/components/Footer.jsx

*Enter the issue title here-* visitors count and star us button added in footer #319 done
- [ X] I have provided the issue title.
---
*Describe the aim of the project-* for cryptocurrency and this issue helps you to famous your repo
- [X ] I have described the aim of the project.
---
**Please mention your name.**   
*Enter your name here-* Vinay Anand Lodhi
- [X ] I have provided my name.
---
*Enter your GitHub ID here-* VinayLodhi1712
- [X ] I have provided my GitHub ID.
---
*Enter your participant role here-* GSSOC and Hactoberfest
- [ X] I have …

visitors count and star us button added in footer #319 done

---

src/App.js
src/components/Footer.jsx
src/pages/ProfitLoss/ProfitLoss.css
src/pages/ProfitLoss/ProfitLoss.js

This PR introduces a dedicated Profit/Loss tracking page within the Crypto Tracker application. Key updates include:
Route Integration: Added route to App.js to display the new Profit/Loss page.
Footer Update: Added navigation link in the footer for easy access to the Profit/Loss tracking feature.
Profit/Loss Page: Created an initial layout for the Profit/Loss page, where users can view their portfolio's performance, including potential gains and losses based on asset value changes.
'Fixed #260 '
https://github.com/user-attachments/assets/32f8c737-8dbd-400e-b8a2-9dd2c5158b79
@vanshchauhan21  done

Add Profit/Loss Options in Portfolio for Crypto Tracker 

---

public/index.html
src/components/Common/Header/index.js
src/components/Common/Header/styles.css

Fixed #324 
---
There was no logo in the navbar
---
Irtesaam
---
irtesaam
---
GSSoC
WoB
Hacktoberfest
---
*Closes: #324 *
---
Added logo in navbar
---
---
Before : 
After : 
---

added CryptoTracker logo in navbar

---

src/App.js
src/components/Footer/Footer.jsx
src/pages/CryptoMarket24h/CryptoMarket24h.css
src/pages/CryptoMarket24h/CryptoMarket24h.js

- Added 24h crypto market page
closes #311 
https://github.com/user-attachments/assets/3b08fab0-4953-42f5-88b7-1a5626e00fba

Added 24h crypto market page

---

src/components/Common/Header/MobileMenuButton.css
src/components/Common/Header/drawer.js
src/components/Common/Header/index.js
src/components/Common/Header/styles.css

*Enter the issue title here-* Need only one either sign up or log in
---
*Describe the aim of the project-* To make the navbar looks beautiful, like as you can see we can go to the log in page through sign up page, so no need to add another option for log in.
---
---
---
---
*Closes: #333 *
---
**Give a clear description of what …

Need only one either sign up or log in

---

src/index.css
src/pages/Login.js
src/pages/Signup.js

*Enter the issue title here-* Enhance log in and log out page
---
*Describe the aim of the project-* I saw that the text is not in the middle(see in the screenshot)
---
---
---
---
*Closes: #332 *
---
*Describe your changes here-* Now it looks like this,i change …

Enhance log in and log out page

---

src/App.js
src/components/Footer/Footer.jsx
src/pages/EthereumRainbow/EthereumRainbowChart.js
src/pages/EthereumRainbowChart.js

Added Ethereum Rainbow Chart
---
GSSOC - Ext
---
*Closes: #313 
---
---
--- locally
https://github.com/user-attachments/assets/63ef7ab8-0dd7-43c9-bcfb-72a9319c6639

Added Ethereum Rainbow Chart

---

src/pages/BitCoinRainBow/BitcoinRainbowChart.css
src/pages/BitCoinRainBow/BitcoinRainbowChart.js

fixed #309 
This update introduces a "Learn More" section on the Bitcoin Rainbow Chart page
https://github.com/user-attachments/assets/02aa6120-7468-413f-8d63-c89bc4b1b677

Added learn more section on bitcoin rainbow chart Page

---

src/components/Common/Header/styles.css

Improve Navbar UI for Dark Mode Compatibility
---
In dark mode, the current navbar elements lack visual contrast, affecting readability and user navigation. This update will adjust the color scheme of the navbar text, icons, and background for better alignment with dark mode aesthetics, improving the user experience across pages in dark mode.
*Closes: #361*
----

Improve Navbar UI for Dark Mode Compatibility

---

src/App.css

Fixed #366 
---
The footer didn't had the dark mode support
---
Irtesaam
---
irtesaam
---
GSSoC
WoB
hacktoberfest
---
*Closes: #366 *
---
Added dark mode theme to the footer using [data-theme="dark"] property for footer
---
---
Before : 
https://github.com/user-attachments/assets/45c40231-9f90-46c8-addc-92502067ccbd
After : 
https://github.com/user-attachments/assets/bbf38b41-42d4-4d49-a239-c20ec7121d12
---

added dark mode for the footer

---

README.md

added social links to the footer of read me
---
to let users reach you
- [x ] I have described the aim of the project.
---
Amiya singh
---
amiya-cyber
- [x ] I have provided my GitHub ID.
---
GSSOC
- [x ] I have mentioned my participant role.
---
**Enter the issue number that will be closed through …

added social links to the footer of read me

---

src/components/Common/Contributors Card/ContributorCard.css
src/pages/Contributors.css
src/pages/Contributors.js

*Enter the issue title here-* Add styles in contribute section
---
*Describe the aim of the project-* Add github link option
---
---
---
---
*Closes: #359 *
---
*Describe your changes here-* 
Here you can see in this picture , i add some style and add profile link. …

Add styles in contribute section

---

src/App.js
src/components/Footer.jsx
src/pages/Track NFT/TrackNFTs.css
src/pages/Track NFT/TrackNFTs.js

*Enter the issue title here-* Add new page about How to Track NFTs on Crypto Tracker
---
*Describe the aim of the project-* Add new page about How to Track NFTs on Crypto Tracker
---
---
---
---
*Closes: #358 *
---
*Describe your changes here-* Add new page.
--- …

Add new page about How to Track NFTs on Crypto Tracker

---

package-lock.json
src/pages/CryptoConverter.css

fixed #347 
Enhanced dark mode styles  on crypto converter page 
https://github.com/user-attachments/assets/0b8a54e1-2611-4e65-af10-0132f1fd3578

Enhance dark mode  style

---

src/App.js
src/components/Footer.jsx
src/pages/Cryptoreward/Cryptoreward.css
src/pages/Cryptoreward/Cryptoreward.js

*Enter the issue title here-* Add new page about learn about crypto tracker reward
---
*Describe the aim of the project-* Add new page about learn about crypto tracker reward
---
*Enter your name here-* Souvik
---
---
---
*Closes: #356 *
---
*Describe your changes here-* Add new page about learn about …

Add new page about learn about crypto tracker reward

---

src/components/Learn.css

Adding HOVER effect to the learn Section
---
---
amiya singh
---
amiya-cyber
---
GSSOC
- [x ] I have mentioned my participant role.
---
*Closes: #375 
- [x ] I have provided the issue number.
---
---
- [ x] …

Adding HOVER effect to the learn Section

---

backend/.gitignore
backend/controller/ContactController.js
backend/package-lock.json
backend/package.json
backend/routes/contactroutes.js
backend/server.js
package-lock.json
package.json
src/pages/Contactus/Contactus.jsx

issue number #379
added send email functionality upon form submission by the user 
images:
send message:
email:

added send email functionality

---

src/components/Common/InDepthAnalysis/InDepthAnalysis.css
src/components/Common/InDepthAnalysis/InDepthAnalysis.js
src/components/LandingPage/MainComponent/index.js

This PR introduces a new "In-Depth Profit & Loss Analysis" section on the Landing Page, allowing users to connect their wallet for detailed financial insights. It includes a video asset as a background element to enhance visual appeal, along with the new InDepthAnalysis component for modular integration.
'fixed #335' @vanshchauhan21  done
https://github.com/user-attachments/assets/d802ff98-921d-4433-9b8d-4e22831c1ab6

Add In-Depth Profit & Loss Analysis Section with Wallet Integration

---

src/App.js
src/components/Footer.jsx
src/pages/BitCoinRainBow/BitcoinRainbowChart.js

- Fetch data dynamically from gecko API in Bitcoin rainbow chart
Fixes #352 
https://github.com/user-attachments/assets/51793c48-13f6-45e8-8114-ae14a93677df

Fetch data dynamically from gecko API in Bitcoin rainbow chart

---

src/App.js
src/components/Footer.jsx
src/pages/BTCDominance/BTCDominance.css
src/pages/BTCDominance/BTCDominance.js

fixed #310 
Added  BTC Dominance Chart to Website
https://github.com/user-attachments/assets/9d3899c4-df25-4442-acb5-bc0a0ac554f1

Created new BTC Dominance chart 

---

src/App.js
src/components/Footer.jsx
src/pages/Cryptoreward/Cryptoreward.css
src/pages/Cryptoreward/Cryptoreward.js

This PR adds a dedicated page for Crypto Tracker Rewards, detailing what rewards are, how users can earn them, and the benefits of participation. The page includes styled sections for clarity and incorporates dark mode support for improved accessibility. Additionally, it updates the App component and Footer to integrate links to this new rewards page.
'fixed #328 
@vanshchauhan21 Done
Uploading Redfdssf.mp4…

Create Separate Page for Crypto Tracker Rewards

---

src/pages/Contactus/Contactus.jsx

issue number #391 
the contact form is visible in the dark mode

dark mode form color

---

src/App.js
src/components/Common/MarketCard/MarketCard.css
src/components/Common/MarketCard/MarketCard.js
src/components/Footer.jsx
src/pages/MarketUpdate/MarketUpdate.js

This PR introduces a new MarketUpdate page and a reusable MarketCard component. It also includes updates to App.js and Footer to integrate these additions and ensure smooth navigation to the MarketUpdate section.
'fixed #415 @vanshchauhan21 Done
Uploading Marg.mp4…

Add MarketUpdate Page and MarketCard Component

---

package-lock.json
package.json
src/components/Common/FreeTrial/FreeTrial.js
src/components/Common/Header/index.js
src/components/Common/InDepthAnalysis/InDepthAnalysis.css
src/components/Common/InDepthAnalysis/InDepthAnalysis.js
src/components/Common/OurVision/OurVision.js
src/components/LandingPage/MainComponent/index.js
src/components/LandingPage/MainComponent/styles.css

issue number #412 
added animation on the homepage and also fixed placement of some elements
video:
https://drive.google.com/file/d/1dyQA1cNkSN--GYr9XhRP2Hm8tqZwubJI/view?usp=sharing
please add gssoc-ext and level2 before merge @vanshchauhan21

added animation upon scroll in the home page

---

src/components/Footer.jsx

🧑‍💻: Enhance star button
---
**Yash K. Saini**
---
[yashksaini-coder](https://github.com/yashksaini-coder)
---
GSSoC-Ext
---
Closes: #338
---
This pull request includes enhancements to the `Footer` component in `src/components/Footer.jsx` to improve user interaction and visual feedback. The main changes involve adding animations and hover effects.
Enhancements to `Footer` component:
* Added transition effects for scaling and …

✅ Enhanced the Star US button

---

src/pages/TermCondition.css

Adjust content  color  for better visibility

---

package-lock.json
src/App.js
src/components/Footer.jsx
src/pages/HelpCenter/HelpCenter.css
src/pages/HelpCenter/HelpCenter.js
src/pages/HelpCenter/HelpCenter.json

This pull request addresses the integration of a Help Center link in the footer of the application, which proved to be challenging due to several factors.
API Calling Issues:
Encountered difficulties while trying to fetch relevant data from external APIs. This included handling CORS issues and managing asynchronous calls effectively to ensure the application could dynamically render Help Center information without lag.
JSON Data Integration:
Developed a JSON structure to represent Help Center topics and descriptions, which required careful planning to ensure the data was easily consumable by React components. Challenges included ensuring that the data was properly formatted and could be efficiently mapped to UI elements.
Dynamic Rendering:
Implemented functionality for dynamic rendering …

Challenging Implementation of Help Center Link in Footer: Navigating API and JSON Complexities

---

src/components/Dashboard/TopCoinsTable/LineGraph.js
src/components/Dashboard/TopCoinsTable/TopCoinsTable.js
src/components/Dashboard/TopCoinsTable/styles.css
src/pages/Dashboard.js

Closes: #395
---
https://github.com/user-attachments/assets/588c90d8-385b-41ae-bcd0-7314e0865780
---

Added table of top 5 coins in dashboard

---

src/App.js
src/components/Footer.jsx
src/pages/TermsOfUse.css

Resolved dark mode display issues by adjusting theming and styles in the App component, Footer, and Terms of Use page. Ensured consistent text and background color transitions when switching between light and dark modes.
'Fixed #417  @vanshchauhan21  Done
https://github.com/user-attachments/assets/a94e829d-fca9-4922-ad77-b8869e9d327b

Fix Dark Mode Display Issues Across App, Footer, and Terms of Use Page

---

src/components/Common/Header/index.js

issue number #410 
i fixed the navbar now it is responsive 
image2:

fixed navbar

---

src/pages/Pro-Free-Subscribtion/ProFreeSubcription.js

here are the some changes did in the subscription page 
@vanshchauhan21  once go through this i have updated my code .
let me know if anything have to update or if its not working

profeesubscription.js

---

src/pages/CryptoCard/Cryptocard.css
src/pages/CryptoCard/Cryptocard.js

fixed #402 
https://github.com/user-attachments/assets/52f7e5c0-2bd9-41f9-82ba-2ff1b661703e

Added a "How to Buy Crypto Card" Guide Page

---

src/App.js
src/components/Footer.jsx
src/components/PageNotFound/PageNotFound.jsx

Implemented auto-redirect functionality that navigates the user to the homepage when an invalid URL is accessed.
Set a delay of 3 seconds before redirecting.
Enhanced the user experience by providing a smoother transition for invalid routes.
'fixed #432  @vanshchauhan21  Done
https://github.com/user-attachments/assets/5158523b-8c0a-4f44-825c-d9e04156efa4

Auto Redirect to Home Page on Invalid URL After 3 Seconds 

---

src/App.js
src/pages/DefiAssets/DefiAssets.js
src/pages/HelpCenter/HelpCenter.js

Fixed the broken link for the DeFi asset tracking section.
Updated the link to ensure users can now correctly access the page.
Performed testing to verify that the issue is resolved across all relevant components.
'Fixed #436'

Fix Broken Link for DeFi Asset Section 

---

src/pages/Faq.css
src/pages/Faq.js

fixed #399 
Added social media icons on faq page 
on light mode :
on dark mode :

Added social media icons on faq page

---

src/pages/ImpermanentLossCalculator.css
src/pages/ImpermanentLossCalculator.js

fixed #403 
https://github.com/user-attachments/assets/b84b9b1d-8b85-4ea9-947d-0290b9df756e

Added learn more section on impermanent loss calculator  page

---

README.md

Add "Back to Top" Scroll-Up Button in README
Issue No: #394  
---
I have implemented a "Back to Top" scroll-up button in the README file to enhance navigation for users. This feature allows users to quickly return to the top of the document, improving overall user experience.
---
*Enter your name here-* Tatheer Fathima
---
*Enter your GitHub ID here-* T-Fathima
---
*Enter your participant role here-* Contributor in gssoc-ext, WoB, Hacktoberfest
---
*Closes: #394 *
---
It uses smooth scrolling to …

Add "Back to Top" Scroll-Up Button in README

---

src/App.css
src/App.js
src/components/Common/MarketCard/MarketCard.css
src/components/Common/MarketCard/MarketCard.js
src/components/Footer.css
src/components/Footer.jsx

This PR includes the integration of dark mode across the app, enhancing the user experience during night-time usage. It also adds the NFT market update feature by fetching data from a crypto news API. The MarketCard component was updated to display relevant information from these market updates. Additional styling improvements were made to the footer for better UI consistency.
'fixed #466  @vanshchauhan21 
https://github.com/user-attachments/assets/5d2ac386-138d-47a1-8d77-7a738b21564d

Add nft market update route 466

---

src/pages/CryptoMarket24h/CryptoMarket24h.css

corrected darkmode visibility

---

src/components/BitcoinRainbowInfo.css
src/components/BitcoinRainbowInfo.js
src/pages/BitCoinRainBow/BitcoinRainbowChart.js

fixed #444 
https://github.com/user-attachments/assets/683942e7-1826-421d-b693-39a16aea762a

Added Bitcoin Rainbow Information Section

---

src/pages/ProfitLoss/ProfitLoss.css

fixed #489 
https://github.com/user-attachments/assets/65ecbb6f-9675-4830-9552-07695ed833f4

corrected Content visibility issue on Portfolio profit and loss overview 

---

src/pages/Dashboard.js

Removed duplicate footer from dashboard

---

src/pages/EthereumRainbow/EthereumRainbowChart.js
src/pages/EthereumRainbow/EthereumRainbowInfo.css
src/pages/EthereumRainbow/EthereumRainbowInfo.js

fixed #450 
I have made it fully responsive , suitable for dark mode also added some animations 
please provide level 3 for it if possible 
https://github.com/user-attachments/assets/141efe3b-df35-436c-a4db-3f810c8e0129

Added Ethereum rainbow chart info section

---

src/components/Feedback/Feedbacksection.css
src/components/Feedback/Feedbacksection.js
src/pages/CryptoCard/Cryptocard.js
src/pages/Cryptoreward/Cryptoreward.js
src/pages/DefiAssets/DefiAssets.js
src/pages/ProfitLoss/ProfitLoss.js
src/pages/Track NFT/TrackNFTs.js

fixed #461 
Added fully responsive , suitable for dark mode feedback section on each learn more page
https://github.com/user-attachments/assets/48115a97-ab83-4443-9acc-4bcdf4f252c4

Added Feedback section for all learn more pages

---

src/App.js
src/components/Footer.jsx
src/pages/CryptoNews/CryptoNews.js

This pull request introduces the implementation of the CryptoNews page, integrating live crypto news data fetching and pagination functionality. Additionally, layout improvements are made to the Footer component for better user experience and consistency across the application. The App.js file is updated to incorporate the new CryptoNews page route.
@vanshchauhan21  Done 
' fixed #488 '
https://github.com/user-attachments/assets/13f1b89c-dcfa-4752-ae64-5a2882c56e80

"Integrate CryptoNews Page and Layout Enhancements

---

src/App.js
src/components/Footer.jsx
src/pages/Aboutus/Aboutus.jsx

fixed #452 
https://github.com/user-attachments/assets/bed701ae-a4c5-4350-8c99-779b010df0a6

Add new 'About Us' page for website

---

src/App.js
src/components/ContributorAnimation/ContributorAnimation.css
src/components/ContributorAnimation/ContributorAnimation.js
src/components/ContributorAnimation/index.js
src/pages/Contributors.js

fixed #188 
https://github.com/user-attachments/assets/a214d0ee-7810-4683-a53c-9095723c791f

Added animation on scroll on contributor cards

---

src/App.js
src/pages/TrackNFT/TrackNFTs.css
src/pages/TrackNFT/TrackNFTs.js

"Implemented the TrackNFTs page with content detailing NFT tracking, along with light/dark mode styling for the title and descriptions, ensuring a seamless user experience in both themes."
'Fixed #486 '  @vanshchauhan21  Done

"Add TrackNFTs Page with Light/Dark Mode Styling and Content Structure"

---

package-lock.json
package.json
src/components/Learn.jsx
src/components/Roadmap.jsx

*Enter the issue title here-* roadmap added on the learn page
- [X ] I have provided the issue title.
---
*Describe the aim of the project-* Roadmap added to learn cryptocurrency
- [X ] I have described the aim of the project.
---
*Enter your name here-*Vinay Anand Lodhi
- [X ] I have provided my name.
---
*Enter your GitHub ID here-* VinayLodhi1712
- [X ] I have provided my GitHub ID.
---
*Enter your participant role here-* GSSOC Hactoberfest
- [X ] I have mentioned my participant role.
---
**Enter the issue number that …

roadmap added on the learn page

---

src/App.js
src/components/Common/TopButton/index.js
src/components/Dashboard/TopNftsTable/TopNftsTable.js
src/components/Dashboard/TopNftsTable/styles.css
src/pages/Cryptoreward/Cryptoreward.js
src/pages/Dashboard.js

- Added table of top 5 NFTs on dashboard using coingecko API
- Fixed merge conflicts
- Fixed TopButton crash issue
Fixes #493 
---

Added table of top 5 NFTs on dashboard using coingecko API

---

backend/controller/ContactController.js
backend/package-lock.json
package-lock.json
src/App.js

issue number #502
i improved the email template by adding header footer and the cyptotracker image

improved the email template

---

package-lock.json
package.json
src/App.js
src/components/Footer.jsx
src/pages/CryptoQuiz/CryptoQuiz.css
src/pages/CryptoQuiz/CryptoQuiz.js
src/pages/CryptoQuiz/Timer.js

fixed #517 
https://github.com/user-attachments/assets/42ba1109-dedc-4142-9127-c5a87635373a

Added crypto quiz page

---

package-lock.json
package.json
src/components/Testimonials/Testimonials.css
src/components/Testimonials/Testimonials.js
src/pages/Aboutus/Aboutus.jsx

fixed #516 
I have added all these features:
1. Responsive design
2. Utilizes a slider (react-slick) to showcase multiple testimonials
3. Smooth transitions between testimonials with fade effects.
4. Autoplay Functionality
5. Responsive design of navigation arrows and dots for easy use on touch devices.
please add label of level 3 if possible 
https://github.com/user-attachments/assets/3662c999-4948-4e53-85d5-63e5fdf6fc8e

Added users feedback section on about us page

---

src/components/Dashboard/Grid/index.js
src/functions/removeItemToWatchlist.js
src/functions/saveItemToWatchlist.js
src/pages/Watchlist.js

Fixes #495 
https://github.com/user-attachments/assets/bf193460-6c14-44d0-ba4e-7749256418a9

Fix watchlist remove and add coin feature

---

stargazers/.eslintrc
stargazers/.gitignore
stargazers/.prettierrc
stargazers/package-lock.json
stargazers/package.json
stargazers/remotion.config.ts
stargazers/src/Main.tsx
stargazers/src/index.ts
stargazers/src/utils.ts
stargazers/tsconfig.json

✅ Closes: #527
This pull request sets up a new project with essential configurations and initial code for a Remotion-based application. The most important changes include adding configuration files, setting up the project dependencies, and implementing the main application logic.
* Added ESLint configuration in `stargazers/.eslintrc` to extend the Remotion ESLint rules.
* Added `.gitignore` file to ignore common files and directories like `node_modules`, `dist`, and `.env`.
* Added Prettier configuration in `stargazers/.prettierrc` to enforce code formatting rules.
* Added TypeScript configuration in `stargazers/tsconfig.json` with strict type-checking options.
* Created `package.json` to define project metadata, dependencies, and scripts for development, build, and testing.
* Configured …

ci: 🎡 remotion studio setup

---

src/components/Common/Header/styles.css

*Enter the issue title here-* Enhance the navbar
---
I add the shadow when we switch to the dark theme.
---
---
---
---
*Closes: #526  *
---
---
---
**Describe how your …

Enhance the navbar

---

package-lock.json
src/App.js
src/pages/Cryptoreward/Cryptoreward.css
src/pages/Cryptoreward/Cryptoreward.js

Refactor the Crypto Reward page by updating the layout, enhancing CSS styling, and refining component structure. This PR also includes dependency updates and necessary routing adjustments in App.js to improve navigation.
@vanshchauhan21 Done 
'fixed #542 '
https://github.com/user-attachments/assets/77d0aa8b-8a0e-4407-8a1b-b56da3d9646e

Improve Crypto Reward Page Structure and Styling

---

src/App.js
src/components/Footer.jsx
src/pages/Methodology/Methodology.css
src/pages/Methodology/Methodology.js

fixed #547 
https://github.com/user-attachments/assets/459c2dc7-c305-4cb4-9d0f-1c465246f23e

created responsive  methodology page  with attractive UI

---

src/App.js
src/components/Footer.jsx
src/pages/Sitemap/Sitemap.css
src/pages/Sitemap/Sitemap.js

fixed #548 
added fully functional responsive site map 
https://github.com/user-attachments/assets/5137995b-1c57-4e0b-baba-712eb2288069

Created sitemap 

---

src/components/Common/MarketCard/MarketCard.css
src/components/Common/MarketCard/MarketCard.js
src/pages/MarketUpdate/MarketUpdate.js

This PR refines the Market Update page by implementing a grid layout for displaying market data in an organized format. Enhancements include improved card styles, animations, and hover effects for better user experience and visual appeal.
'fixed #545 ' 
@vanshchauhan21  done
https://github.com/user-attachments/assets/af3a8027-8074-4046-b880-d51a47562752

Improve Market Update Page: Grid Layout, Card Style Enhancement, and Animation Updates

---

src/App.js
src/components/CustomFearAndGreedIndicator.css
src/components/CustomFearAndGreedIndicator.js
src/pages/FearAndGreedIndex/FearAndGreedIndex.css
src/pages/FearAndGreedIndex/FearAndGreedIndex.js

fixed #538 
features I have added :
1. Dynamic Emoticons
2. Animated Value Display
3. 3D Effects
4. Hover Effects
5. Color-Coded Indicator Bar
6. Responsive Design
7. Last Updated Timestamp
8. suitable for light mode and dark mode
https://github.com/user-attachments/assets/0717745f-d619-41bd-9f5c-ede09482edf0

Integrate Advanced Fear and Greed Indicator

---

src/components/Common/Header/styles.css
src/pages/Privacy-Policy/PrivacyPolicy.css
src/pages/Privacy-Policy/PrivacyPolicy.js

This PR updates the Privacy Policy page to ensure it aligns with typical crypto industry standards. It includes improved styling for readability, consistent layout updates in the Header component, and structured Privacy Policy content that reflects crypto-specific requirements.
'fixed #575 ' 
@vanshchauhan21 Done
https://github.com/user-attachments/assets/088ad4b8-1a70-476e-8980-efcf6cf75320

Enhance Privacy Policy Page Styling and Content for Consistency with Crypto Standards

---

src/components/Common/FreeTrial/FreeTrial.js
src/pages/Pricing/Pricing.js

Implemented a click handler for the "Start My Free Trial" button to redirect users to the Pricing page.
Ensured that the Pricing page scrolls to the top on load for improved user experience.
'fixed #573 ' 

Add Click Handler for "Start My Free Trial" Button and Scroll-to-Top in Pricing Page

---

package-lock.json
package.json
public/index.html
src/App.js
src/components/Common/Footer/footer.js
src/components/Footer.jsx
src/pages/Earn/Earn.css
src/pages/Earn/Earn.js

fixed #534 
https://github.com/user-attachments/assets/b080142e-b2af-4f5c-867b-50bd510bfa47

Created responsive earn page

---

src/pages/GeminiAIChat/GeminiAIChat.jsx

✅ Closes: #553
*🧑‍💻: Enhance UI of the Gemini Chat*
---
*Enter your name here-* **Yash K. Saini**
---
*Enter your GitHub ID here-* [yashksaini-coder](https://github.com/yashksaini-coder)
---
*Enter your participant role here-* GSSoC-Ext
---
*Closes: #issue-number* #553
---
This pull request includes several enhancements and bug fixes to the `GeminiAIChat` component. The most important changes involve …

perf: ⚡️ Enhance the UI and proper response return format

---

package-lock.json
src/components/Common/Header/index.js
src/components/Common/Header/styles.css

issue number #579 
i fixed the navbar element placement and alignment 
i was like this before:

fixed the navbar

---

src/components/Dashboard/Grid/index.js
src/components/Dashboard/Tabs/index.js

issue number #581 
added animation in the grid and list tabs in the dashboard page 
grid
list:

added animation

---

src/App.js
src/components/Footer.jsx
src/components/Sidebar.css
src/components/Sidebar.js
src/pages/Blogs/Blog.css
src/pages/Blogs/Blog.js
src/pages/Blogs/BlogPost.css
src/pages/Blogs/BlogPost.js

fixed #531 
https://github.com/user-attachments/assets/8bebc52b-f273-4cd6-b545-2f763a29e57d

Build responsive blog page

---

src/App.js
src/components/Footer.jsx
src/pages/CompoundInterestCalculator.css
src/pages/CompoundInterestCalculator.js

Added Compound Interest Calculator
---
---
amiya singh
- [x ] I have provided my name.
---
amiya-cyber
- [x ] I have provided my GitHub ID.
---
GSSOC
- [x ] I have mentioned my participant role.
---
*Closes: #566 
- [ x] I have provided the issue number.
---
**Give a …

Added Compound Interest Calculator

---

package-lock.json
src/App.js
src/components/Footer.jsx
src/pages/MarginCalculator.css
src/pages/MarginCalculator.js

added margin calculator
---
- [ x] I have described the aim of the project.
---
amiya singh
---
amiya-cyber
---
---
*Closes: #567 
- [x ] I have provided the issue number.
---
**Give a clear description of what you have added or …

added margin calculator

---

package-lock.json
src/App.js
src/components/Footer.jsx
src/pages/DividendCalculator.css
src/pages/DividendCalculator.js

added dividend calculator
---
added dividend calculator
- [x ] I have described the aim of the project.
---
amiya singh
- [x ] I have provided my name.
---
amiya-cyber
- [ x] I have provided my GitHub ID.
---
---
*Closes: #607 
---
**Give a clear description of what …

added dividend calculator

---

package-lock.json
public/index.html
src/App.js
src/components/BackToTopButton/BackToTopButton.css
src/components/BackToTopButton/BackToTopButton.js
src/components/Footer.jsx
src/index.css

*Enter the issue title here-* Fixed chatbot and scroll-to-top buttons alignments and made it responsive.
---
*Describe the aim of the project-* The aim of the project was to fix alignments of both scroll-to-top and chatbot buttons. 
---
*Enter your name here-* Nakul Krishnakumar
---
*Enter your GitHub ID here-* nakul-krishnakumar
---
---
*Closes: #602 * 
---
**Give a clear description of what you have added or …

Fixed chatbot and scroll-to-top buttons alignments and made it responsive.

---

src/pages/KnowledgeHub/KnowledgeHub.css
src/pages/KnowledgeHub/KnowledgeHub.js
src/pages/Useful Tools/ProfitReturnCalculator.js

fixed #597 
https://github.com/user-attachments/assets/eabbabd9-30a4-4bbd-80ba-ac6c39b04385

Created knowledge hub on profit  return calculator

---

src/components/LandingPage/MainComponent/index.js
src/pages/Real-timeMarket-data/Marketdata.css
src/pages/Real-timeMarket-data/Marketdata.js

**Please enter the title of the issue related to your pull request.**  Adding a new section to the main page of the website "Real-Time Market Data"
*Enter the issue title here-* #619 
https://github.com/user-attachments/assets/cbaec641-88bd-4b25-8e44-4c51c00d5334
**Please mention your name.**  Shriya D
---
**Please mention your GitHub ID.**  shriyadindi
---
*Enter your participant role here-* gssoc-extd
---
*Closes: #issue-number* #619
---
---

Adding a new section to the main page of the website "Real-Time Market Data"

---

src/App.js
src/components/Footer.jsx
src/pages/Useful Tools/Investmentreturncalculator.js

*Enter the issue title here-* Adding an "Investment Return Calculator"
https://github.com/user-attachments/assets/18dcae5c-6be0-4fc7-9a3a-80a95379d460
Shriya D
---
shriyadindi
---
gssoc-extd
---
#624 

Adding an "Investment Return Calculator"

---

stargazers/src/Content.tsx
stargazers/src/cache.ts
stargazers/src/gh-styles.css

✅ Closes: #620 
This pull request introduces new functional to display stargazers of a repository, including the addition of a new `Content` component, caching mechanisms, and styles for the stargazers' display. The most important changes include the creation of the `Content` component, the addition of caching functions, and the inclusion of new CSS styles.
New Components and Functionality:
* [`stargazers/src/Content.tsx`](diffhunk://#diff-a23fdc6e05742586e03f742a0e689408d35c3b1e26d416b042835c0775e35182R1-R162): Added a new `Content` component to display stargazers, including a nested `StarBox` component for individual stargazer details.
Caching Mechanisms:
* [`stargazers/src/cache.ts`](diffhunk://#diff-5ace607059b1e5bea167e6458a9d3b5607fe54cc1a9093103b6a4e9492bcdb1bR1-R68): Introduced …

Remotion application componenets done

---

src/components/Dashboard/Grid/index.js
src/components/Dashboard/List/index.js

issue number #583 
now the text is visible 
grid:
list:
they are now visible @vanshchauhan21

fixed the text color for light mode

---

src/components/Common/FreeTrial/FreeTrial.css
src/components/Common/FreeTrial/FreeTrial.js
src/components/Common/InDepthAnalysis/InDepthAnalysis.css

*Enter the issue title here-* Made freeTrial and InDepthAnalysis component responsive
---
*Describe the aim of the project-* The aim of the project was to make the above mentioned components responsive for all screen sizes.
---
*Enter your name here-* Nakul Krishnakumar
---
*Enter your GitHub ID here-* nakul-krishnakumar
---
---
*Closes: #599 *
---
**Give a clear description of what you have added or modified.** …

Made freeTrial and InDepthAnalysis component responsive

---

package-lock.json
src/App.js
src/pages/DefiAssets/DeFiAssetStyles.css
src/pages/DefiAssets/DefiAssets.js

fixed #629 
https://github.com/user-attachments/assets/8019df41-0463-4d68-82d2-ad4129bc22a8

Enhanced defi assets styling

---

package-lock.json
src/App.js
src/components/Footer.jsx
src/pages/CodeOfConduct/CodeOfConduct.css
src/pages/CodeOfConduct/CodeOfConduct.js

**Code of Conduct Addition for CryptoTracker Platform**  
*This PR adds a dedicated Code of Conduct page to the CryptoTracker platform, setting clear expectations for user behavior.*
fix #511 
---
The goal of this project is to establish clear guidelines for acceptable behavior, foster a respectful and inclusive community, and ensure a safe and positive environment for all users.
---
Shariq
---
shariq2003
---
GSSOC
---
Closes: #511
---
- Added a **Code of …

add code of conduct in footer

---

src/App.js
src/components/Footer.jsx
src/pages/PercentageChangeCalculator.css
src/pages/PercentageChangeCalculator.js

added percent change calculator
---
added percent change calculator
---
amiya singh
- [x ] I have provided my name.
---
amiya -cyber
- [x ] I have provided my GitHub ID.
---
---
*Closes: #606 
- [ x] I have provided the issue number.
---
**Give a clear description of …

added percent change calculator

---

package-lock.json
package.json
src/App.js
src/pages/Login.js

Adding remember checkbox and forgot password to the login page.
Shriya D
---
shriyadindi
---
gssoc-extd
---
*Closes: #issue-number* 
#623 
---
---

Adding remember checkbox and forgot password to the login page

---

package-lock.json
src/components/SecuritySection/SecuritySection.css
src/components/SecuritySection/SecuritySection.js
src/pages/CryptoProfitCalculator.js

fixed #596 
https://github.com/user-attachments/assets/4b59b267-b9ad-4871-8a9b-d676490e4a6c

Strengthen User Trust with "Fortified Security for Your Digital Assets" on Crypto Profit

---

src/pages/DefiAssets/DeFiAssetStyles.css

Fixed #530 
This update addresses critical visibility issues on the DeFi Asset Tracking page, where content was challenging to read. Adjustments have been made to ensure text contrast is appropriate in both dark and light modes. Additionally, layout elements have been restructured to prevent overlapping and enhance readability, delivering a more accessible and user-friendly interface.
https://github.com/user-attachments/assets/12b7f77a-2807-418e-9730-f2b9db59306f

Fix content visibility issues on DeFi Asset Tracking page

---

src/components/LoveOurWebsite/LoveOurWebsiteCarousel.css

Enhance styling of Fear and Greed Index page for better user experience

---

src/components/Common/Price Card/PriceCard.css
src/components/Dashboard/Grid/index.js
src/components/Dashboard/Grid/styles.css
src/pages/Contactus/Contactus.jsx
src/pages/Pricing/Pricing.css

*Enter the issue title here-improving visibility and appearance in light mode*
---
*Describe the aim of the project- improving visibility and appearance in light/dark mode of multiple pages -> pricing, contact us, grid displayed in dashboard*
---
*Enter your name here- Riya Chauhan*
---
*Enter your GitHub ID here-Riyachauhan11*
---
*Enter your participant role here-GSSOC ext*
---
*Closes: #614*
---
**Give a clear description of what you have added or …

fixing light and dark mode appearance in multiple pages

---

src/App.js
src/components/Footer.jsx
src/components/PortfolioChart.js
src/components/PortfolioSummary.js
src/pages/UltimateCryptoPortfolioTracker/UltimateCryptoPortfolioTracker.css
src/pages/UltimateCryptoPortfolioTracker/UltimateCryptoPortfolioTracker.js

fixed #631 
https://github.com/user-attachments/assets/7320eb1d-dc35-42ba-93d7-72cfae79b621

Developed and Integrated Ultimate Crypto Portfolio Tracker Page 

---

src/components/CryptoProfitCalculatorInfo.css
src/components/CryptoProfitCalculatorInfo.js
src/pages/CryptoProfitCalculator.js

fixed #595 
https://github.com/user-attachments/assets/91087d00-4eb6-4ace-91e1-1b220cd725e7

Developed an Essential, Feature-Rich Information Hub for CryptoProfit Calculator

---

src/pages/CompoundInterestCalculator.js
src/pages/CompoundInterestCalculator/MasterTheMath.css
src/pages/CompoundInterestCalculator/MasterTheMath.js

fixed #663 
https://github.com/user-attachments/assets/24c95d3c-ffae-4cd1-acb4-0b6742418e2b

 Incorporate a 'Master the Math' Section for the Compound Interest Calculator

---

src/components/LandingPage/MainComponent/index.js
src/components/SwapWithBestRates/SwapWithBestRates.css
src/components/SwapWithBestRates/SwapWithBestRates.js

Add the "Swap With Best Rates" component with relevant functionality and UI, including the integration of best swap paths and rates across various liquidity sources.
'fixed #592 '
https://github.com/user-attachments/assets/65f71844-f08f-4599-bb76-17b4b7495eee

Implement Swap With Best Rates Component

---

src/components/LandingPage/MainComponent/index.js
src/pages/AnalyzeAssets/PortfolioComparison.css
src/pages/AnalyzeAssets/PortfolioComparison.js

Implemented the PortfolioComparison component to display the comparison between user portfolio performance and the overall market.
"fixed #590 '
https://github.com/user-attachments/assets/a1c51412-353c-457a-8321-6fdb238c5789

Added PortfolioComparison component for portfolio vs market section

---

src/components/BuyBitcoinSection/BuyBitcoinSection.css
src/pages/BitCoinRainBow/BitcoinRainbowChart.js

This PR introduces a dynamic loading indicator to improve the user experience during asynchronous rendering of data on the Bitcoin Rainbow Chart. It ensures a smoother transition while waiting for data to load.
'fixed #589 '
https://github.com/user-attachments/assets/13671068-1866-4780-9a8b-c113e186ae61

Implement Dynamic Loading Indicator for Asynchronous Rendering on the Bitcoin Rainbow Chart Interface

---

src/components/BuyBitcoinSection/BuyBitcoinSection.css
src/components/Common/Price Card/PriceCard.css
src/pages/EthereumRainbow/EthereumBuySection.css
src/pages/Pricing/Pricing.css
src/pages/Pricing/Pricing.js

Fixed #665 
This update addresses a significant content visibility issue on the Price page, ensuring essential information is fully readable in both light and dark modes. Adjustments include background color corrections, text visibility enhancements, and consistent styling elements that reinforce readability and visual consistency. This fix restores core functionality and improves user trust by providing a reliable and accessible interface on the Price page.
https://github.com/user-attachments/assets/d729c5de-895c-4b88-9e4f-02538ebc3e5f

 Fix catastrophic content visibility on Price page

---

src/App.js
src/pages/Useful Tools/Investmentreturncalculator.js

Supercharge User Engagement with an 'Expert Insights & Pro Tips' Section for the Investment Return Calculator

---

src/App.js
src/pages/PercentageChangeCalculator.css
src/pages/PercentageChangeCalculator.js

Added info section

---

src/pages/AffiliateProgram/AffiliateProgram.js

launched affiliate program

---

src/pages/ImpermanentLossCalculator.js

Implement Added Dynamic "Did This Answer Your Question?" Feedback and Comprehensive "Learn More About Impermanent Loss Calculator" Section

---

src/pages/Contributors.css
src/pages/Contributors.js

Enhance d User Interaction with a Streamlined "Show More" Button for the Contributors Page

---

src/components/LandingPage/MainComponent/index.js
src/components/PlatformStatistics/PlatformStatistics.css
src/components/PlatformStatistics/PlatformStatistics.js

Added a new PlatformStatistics component to display statistics for 100+ exchanges, 200+ wallets, 1,000+ DeFi protocols, and 20,000+ coins. Integrated the component into the MainComponent for better crypto portfolio management and added a corresponding CSS file for styling.
'fixed #594 '

Integrate Platform Statistics Component for Crypto Management Overview

---

src/App.js
src/pages/CompoundInterestCalculator.css
src/pages/Cookie-Policy/CookiePolicy.css
src/pages/Cookie-Policy/CookiePolicy.js
src/pages/CryptoCard/Cryptocard.css
src/pages/CryptoProfitCalculator.css
src/pages/Dashboard.js
src/pages/DividendCalculator.css
src/pages/MarginCalculator.css
src/pages/Refund Policy/RefundPolicy.css
src/pages/cics.css

Fixed #696 
https://github.com/user-attachments/assets/fb414d95-3514-4ef8-ad62-1df8f9d3b958

 Revamp Cookie Policy page UI for improved clarity and user engagement

---

src/pages/Faq.js

Added feedbacksection on faq page 

---

src/pages/Disclaimer/Disclaimer.css

Fixed #700 
https://github.com/user-attachments/assets/6e1065a4-6f57-408c-9b12-c3f71042f565

Enhance Disclaimer Page UI for improved accessibility and clarity

---

src/App.js
src/pages/CompoundInterestCalculator.css
src/pages/CryptoCard/Cryptocard.css
src/pages/CryptoProfitCalculator.css
src/pages/Dashboard.js
src/pages/DividendCalculator.css
src/pages/MarginCalculator.css
src/pages/cics.css

Fixed #693 
https://github.com/user-attachments/assets/ccfbccd5-2ad2-4163-b1c6-0bb6c3588247

Resolve content visibility issues in dark mode on 'How to Buy Crypto with a Card' page

---

src/pages/BitCoinRainBow/BitcoinRainbowChart.js

Added Feedback

---

src/App.js
src/pages/CompoundInterestCalculator.css
src/pages/CryptoCard/Cryptocard.css
src/pages/CryptoProfitCalculator.css
src/pages/Dashboard.js
src/pages/DividendCalculator.css
src/pages/MarginCalculator.css
src/pages/Refund Policy/RefundPolicy.css
src/pages/cics.css

Fixed #695 
https://github.com/user-attachments/assets/94bec7bc-f72c-4069-92c2-8901558aa1af

Revamp Refund Policy page UI for improved readability and user experience

---

src/pages/EthereumRainbow/EthereumRainbowChart.js

Added feedback on ethereum

---

src/pages/Aboutus/Aboutus.jsx

Added logo on about us page

---

src/pages/FearAndGreedIndex/FearAndGreedIndex.css
src/pages/FearAndGreedIndex/FearAndGreedIndex.js

Integrated Comprehensive "Fear and Greed Index" Information Section to Enhance User Insights and Market Understanding

---

src/pages/Useful Tools/ProfitReturnCalculator.js

 Integrated Comprehensive "Crypto Profit Calculator" Information Section to Maximize User Understanding and Utility

---

src/pages/CryptoMarket24h/Crypto24HourReport.css

added news for crypto market

---

src/pages/Contactus/contact.css

Corrected contact form styling

---

src/components/MarketStats/MarketStats.css
src/pages/BTCDominance/BTCDominance.css

Integrated Robust Key Market Indicators on BTC Dominance Chart Page for Enhanced Analytical Depth

---

src/pages/Pricing/Pricing.css

Corrected content visibility on pricing container

---

README.md

UI Enhancement for README file to improve structure and readability 
---
To enhance the user interface of the README file for better presentation and easy navigation, making it more user-friendly and visually appealing.
Removed duplicate sections 
---
*Enter your name here-* Tatheer Fathima
---
*Enter your GitHub ID here-* T-Fathima
---
*Enter your participant role here-* Contributor in  GSSoC-ext , Hacktoberfest, WoB
---
*Closes: #641*
---
---
@vanshchauhan21 Could you please review it asap as today is the last day for contributions and assign it with gssoc-ext …

Enhanced the entire UI and structure of readme

---

src/pages/ImpermanentLossCalculator.js

Added key insights on  Impermanent Loss Calculator 

---

README.md

*Add Table of Contents to README*
---
*The goal of the project is to enhance the README by adding a Table of Contents (TOC) to make navigation easier for users.*
---
*Alolika Bhowmik*
---
*alolikabhowmik*
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hacktoberfest).**  
*GSSoC 2024 Contributor*
---
*Closes: #736*
---
*I have added a Table of Contents section to the README to improve its usability and navigation.*
---
**Select the type of change:** …

Add Table of content 

---

src/pages/Aboutus/Aboutus.jsx
src/pages/contributor.js

Fixed #692 
https://github.com/user-attachments/assets/d8c27451-6efd-4de0-9289-25e8b22daab4

Add "Our Contributors" section to About Us page for improved engagement and transparency

---

src/App.js
src/components/Footer.jsx
src/pages/ImpermanentLossCalculator.css
src/pages/ImpermanentLossCalculator.js

Integrated "Did We Answer Your Question?" Feedback Feature on Impermanent Loss Calculator Page

---

src/App.js
src/components/Footer.jsx
src/pages/CompoundInterestCalculator.js

Integrate an In-Depth Educational Info Section for the Compound Interest Calculator 

---

src/pages/defi.css
src/pages/defi.js

Added information section for defi yeild estimator

---

stargazers/src/Main.tsx
stargazers/src/wait-for-no-input.ts

✅ Closes: #610 
This pull request includes changes to the `stargazers` project, focusing on improving functionality and fixing a minor import issue.
* [`stargazers/src/Main.tsx`](diffhunk://#diff-4a5a13e7628d663468b4d71375140bdfe8b4a1409b49d026334a4d9073dafd11L4-R4): Corrected the import statement for `Content` to ensure proper case sensitivity. (`[stargazers/src/Main.tsxL4-R4](diffhunk://#diff-4a5a13e7628d663468b4d71375140bdfe8b4a1409b49d026334a4d9073dafd11L4-R4)`)
* [`stargazers/src/wait-for-no-input.ts`](diffhunk://#diff-2f67891b10e932b7591465ae6d76c381291f5775615b6ece6843deabe5caad84R1-R25): Added a new utility function `waitForNoInput` to handle waiting for no input during non-rendering phases, with proper handling of abort signals. …

Remotion types components completed

---

src/pages/ImpermanentLossCalculator.css
src/pages/ImpermanentLossCalculator.js

Improved styling for give us a star

---

src/pages/Earn/Earn.css

Added color styling

---

src/components/SwapWithBestRates/SwapWithBestRates.css

Enhance Hover Interaction for "Swap with Best Rates" Button with Dynamic Color Change

---

src/components/SecuritySection/SecuritySection.css
src/pages/Pricing/Pricing.js

Add a dedicated SecuritySection component to the Pricing page with updated styles and layout, enhancing the presentation of security features and benefits for users.
---
To enhance the Pricing page by adding a dedicated SecuritySection component that highlights the security features and benefits for users in a clear and visually appealing manner.
---
Rachit Sahu
---
@RachitSahu26 
---
*Enter your …

 Integrate Enhanced Security Section in Pricing Page

---

src/pages/gfe.css
src/pages/gfe.js

Added information section on gfe

---

src/App.js
src/components/Footer.jsx
src/pages/SIPCalculator.js

---
---
---
---
---
*Closes: #558 
---
---
---
---
- [ …

Added SIP calculator

---

src/components/Sidebar.css
src/pages/Blogs/Blog.css
src/pages/Blogs/BlogPost.css

Fixed #771 
https://github.com/user-attachments/assets/068bc192-7294-4785-aee6-26f73e999eec

Improve UI and functionality of Crypto Tracker blog for enhanced aesthetics and user experience

---

src/App.js
src/components/LandingPage/MainComponent/index.js
src/pages/Feedback.css

Enhancing the Visual Experience of the Feedback Form

---

src/pages/FearAndGreedIndex/FearAndGreedIndex.css

Fixed #764 
https://github.com/user-attachments/assets/d420f32d-e630-447b-99e3-5acb8a4f6d47

Fix dark mode opacity issue on "Fear and Greed Index" page to improve content visibility

---

src/App.js
src/components/LandingPage/MainComponent/index.js
src/pages/ProfitLoss/ProfitLoss.css

Improved profit loss overview

---

src/App.js
src/components/Footer.jsx
src/pages/BreakEvenCalculator.js

Added Breakeven Calculator
---
---
---
---
---
*Closes: #608 
---
---
---
---
**Please …

Added Breakeven Calculator

---

src/App.js
src/pages/Contactus/contact.css

Corrected contact us

---

src/pages/ico.css
src/pages/ico.js

added info section on ico/ido

---

src/App.js
src/components/Footer.jsx
src/pages/ROICalculator.js
src/pages/SlippageCalculator.js

Added ROI calculator
---
---
amiya singh
---
amiya-cyber
---
---
*Closes: #557 
---
---
- [ x] Bug fix (non-breaking change which fixes an …

Added ROI calculator

---

src/App.js
src/components/Footer.jsx
src/pages/SlippageCalculator.js

---
---
---
---
---
*Closes: #605 
---
---
---
--- …

added slippage calculator 

---

package-lock.json
src/pages/EthereumRainbow/EthereumBuySection.css

#807: Fix blurry text

---

package-lock.json
src/App.js
src/components/Common/Header/index.js
src/components/Common/Header/styles.css
src/components/Footer.jsx

**FRONTEND ISSUE: navbar misaligned**
---
The goal of this project is to improve the UI by fixing the misalignment issue in the navbar and ensuring that it appears correctly across different screen sizes.
---
Aishwarya
---
@AishwaryaChandel27
---
GSSOC 2025
---
Closes: #101
---
Fixed the navbar alignment by adjusting the CSS properties. The items are now correctly centered, and the navbar is responsive across all screen sizes.
---
**Select the type of change:** …

Update navbar with new changes

---

package-lock.json
src/App.js
src/components/Common/Header/index.js
src/components/Common/Header/styles.css
src/components/Footer.jsx

Fixed the frontend issue that was present in the navbar. Also, fixed some redundancy errors that were caused by repetitive imports.
**Light mode**
**Dark Mode**

fixed issue #813

---

src/pages/TrackNFT/TrackNFTs.css

Fix heading color in dark mode

#815: Fix heading color in dark mode

---

index.html
styles.css

This pull request addresses the header misalignment issue in the CryptoTracker website. The following changes were made:
Fixed the alignment of items in the header to prevent them from collapsing or going out of the div.
Added a responsive layout for better display on different screen sizes.
Updated CSS styles to ensure proper spacing and alignment of header elements.
Additionally, external resources like style.css have been linked to maintain consistent styling across the website

Fix Header Alignment and Responsiveness in CryptoTrackerAdd files via upload

---

src/pages/Compare.js

---
---
---
---
---
*Closes: #820 *
---
---
---
---

moved the div downward

---

src/App.js

---
---
---
---
---
---
---
---
--- …

make all the button function

---

src/components/Common/Header/styles.css

make hampburger visible
---
---
---
---
---
---
---
---
--- …

make hampburger visible

---

src/components/Dashboard/List/index.js
src/components/Dashboard/List/styles.css
src/pages/CryptoMarket24h/Crypto24HourReport.css

---
---
---
---
---
---
---
---
--- …

aligned the line between list components

---

src/components/Common/OurVision/OurVision.css
src/components/LandingPage/MainComponent/index.js
src/components/LandingPage/MainComponent/styles.css
src/pages/Marquee/Marquee.css
src/pages/Marquee/Marquee.js

---
---
*Enter your name here- Tanuja Bisht
---
*Enter your GitHub ID here- 141546180
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).**  SWOC
*Enter your participant role here- contributor
---
---
---
---
*Describe your testing process …

Fixed CSS and made slider infinite

---

backend/server.js
package-lock.json

…PI Requests
Include Error Handling for Failed API Requests
- [1 ] I have provided the issue title.
---
To provide real-time cryptocurrency tracking and display relevant financial data to users.
- [ 1] I have described the aim of the project.
---
Drashti Mistry
- [1 ] I have provided my name.
---
https://github.com/DrashtiMistry
- [1 ] I have provided my GitHub ID.
--- …

issue #838 solved BACKEND ISSUE:🚫 Include Error Handling for Failed  API Requests

---

package-lock.json
package.json

*Enter the issue title here-* The previous PR failed to deploy due to a Module Not Found error.
---
---
*Enter your name here-Tanuja bisht
---
*Enter your GitHub ID here-141546180
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).**  SWOC
*Enter your participant role here- contributor
---
---
**Give a clear description of what you have added or modified.**  Added the missing files to ensure all required modules are present
*Describe your changes …

Fix: Updated files to ensure successful deployment

---

index.html
package-lock.json
src/App.js
src/components/Footer.css
src/components/Footer.jsx
src/index.css
styles.css

Footer is updated
Resolves #844

Footer Updated✅

---

backend/.gitignore
backend/package-lock.json
backend/package.json
package-lock.json
package.json
src/App.js
src/pages/CryptoProfitCalculator.css
src/pages/CryptoProfitCalculator.js

🧑‍💻: Urgent Visibility Issue: "Info Hub" Content Inaccessible in Light Mode on Crypto Profit Calculator #778 
- [X ] I have provided the issue title.
---
This pull request resolves the above stated issue of visibility of "Info Hub" in Crypto Profit Calculator
- [X ] I have described the aim of the project.
---
Aastha Bhat
- [ X] I have provided my name.
---
https://github.com/AasthathecoderX
- [X ] I have provided my GitHub ID.
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, …

Added visibility to Crypto Profit Calculator Info Hub

---

src/components/Footer.jsx

Footer fixed now all content are linkable
Resolves #846 
Closes #846
---
---
---
---
---
---
---
---
**Describe how your changes have been tested.** …

Footer Fixed✅

---

src/components/Common/Header/drawer.js
src/components/Common/Header/styles.css
src/components/Footer.jsx

Resolves #234 
Closes #234 
---
---
---
---
---
---
---
---
--- …

Navbar Updated ✅

---

src/components/Common/Header/index.js
src/components/Common/Header/styles.css
src/components/CryptoTrackerManagingTool/CryptoTrackerManagingTool.css
src/components/CryptoTrackerManagingTool/CryptoTrackerManagingTool.js
src/components/LandingPage/MainComponent/index.js
src/components/PlatformStatistics/PlatformStatistics.css
src/components/PlatformStatistics/PlatformStatistics.js
src/index.css
src/pages/Marquee/Marquee.css
src/pages/Marquee/Marquee.js
tailwind.config.js

**GitHub ID:** ali123606  
- Configured **`tailwind.config.js`** with `darkMode: "class"` for better theme management.  
- Implemented **dynamic text colors** using Tailwind for seamless dark/light mode transitions.  
- Integrated **CSS variables** to maintain theme consistency across all components.

Fixed Tailwind Dark Mode & Theme-Based Text Color Sync

---

src/App.js

error hnadling

---

package-lock.json
package.json
src/components/CoinPage/Info/index.js
src/components/CoinPage/Info/styles.css
src/components/CoinPage/LineChart/index.js
src/components/CoinPage/SelectDays/index.js
src/components/CoinPage/SelectDays/styles.css
src/components/CoinPage/ToggleComponent/index.js
src/components/ComparePage/Chart.js
src/components/ComparePage/ChartTab/Tabs.css
src/components/ComparePage/ChartTab/Tabs.js
src/components/ComparePage/SelectCoins/index.js
src/components/ComparePage/SelectCoins/styles.css
src/components/ComparePage/SelectDays/index.js
src/components/ComparePage/SelectDays/styles.css
src/components/Dashboard/List/index.js
src/components/Dashboard/List/styles.css
src/functions/get100Coins.js
src/functions/getCoinData.js
src/functions/getDate.js
src/functions/settingChartData.js
src/pages/Compare.js

*Enter the issue title here-* Compare- page
---
- [] I have described the aim of the project.
---
**Please mention your name.**  Tanuja Bisht
*Enter your name here-* Tanuja Bisht
---
*Enter your GitHub ID here-* 141546180
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).**   Apertre 2.0
*Enter your participant role here-* Contributor
---
---
*Describe your changes here-*  
A more modern and intuitive design for …

Compare page redesign

---

src/components/Dashboard/Grid/styles.css
src/components/Dashboard/List/index.js
src/components/Dashboard/List/styles.css
src/functions/settingChartData.js
src/pages/Compare.js

*Enter the issue title here-* overlapping issue in compare page
---
---
*Enter your name here-*Tanuja Bisht
---
*Enter your GitHub ID here-*Tanujabisht2003
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).** Apertre2.0
*Enter your participant role here-* Contributor
---
---
*Describe your changes here-* Actually my previous commit has some issue which are causing overlapping so i …

overlapping issue

---

package-lock.json
src/components/Footer.jsx

Resolves #867 
Close #867 
---
---
---
---
---
---
---
---
--- …

Ethierum website added

---

package-lock.json
package.json
src/components/CoinPage/Info/index.js
src/components/CoinPage/ToggleComponent/index.js
src/components/ComparePage/Chart.js
src/components/ComparePage/SelectCoins/styles.css
src/components/ComparePage/SelectDays/styles.css
src/components/Dashboard/List/index.js
src/pages/Compare.css
src/pages/Compare.js

*Enter the issue title here-*Responsive UI Fix for Compare Page (Laptop View)
---
---
*Enter your name here-*Tanuja Bisht
---
*Enter your GitHub ID here-*Tanujabisht2003
---
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).**  Apertre2.0
*Enter your participant role here-*Contributor
---
---
*Describe your changes here-* 
Resolved layout and responsiveness issues for the Compare Page on …

Responsive UI Fix for Compare Page (Laptop View)

---

package-lock.json
src/components/Common/FreeTrial/FreeTrial.css
src/components/Common/FreeTrial/FreeTrial.js
src/components/Common/InDepthAnalysis/InDepthAnalysis.css
src/components/Common/InDepthAnalysis/InDepthAnalysis.js
src/components/Common/OurVision/OurVision.css
src/components/Common/OurVision/OurVision.js
src/components/Common/StarButton/StartButton.css
src/components/Common/StarButton/StartButton.js
src/components/CryptoTrackerManagingTool/CryptoTrackerManagingTool.css
src/components/CryptoTrackerManagingTool/CryptoTrackerManagingTool.js
src/components/ExitStrategy/ExitStrategy.css
src/components/ExitStrategy/ExitStrategy.js
src/components/LandingPage/MainComponent/index.js
src/components/LandingPage/MainComponent/styles.css
src/components/LoveOurWebsite/LoveOurWebsiteCarousel.css
src/components/LoveOurWebsite/LoveOurWebsiteCarousel.js
src/components/PlatformStatistics/PlatformStatistics.css
src/components/SwapWithBestRates/SwapWithBestRates.css
src/components/SwapWithBestRates/SwapWithBestRates.js
src/index.css
src/pages/AnalyzeAssets/AnalyzeAssets.css
src/pages/AnalyzeAssets/AnalyzeAssets.js
src/pages/AnalyzeAssets/PortfolioComparison.css
src/pages/AnalyzeAssets/PortfolioComparison.js
src/pages/Marquee/Marquee.css
src/pages/Marquee/Marquee.js
src/pages/Real-timeMarket-data/Marketdata.css
src/pages/Real-timeMarket-data/Marketdata.js

**FRONTEND ISSUE:ui not responsive for mobile tablet users #816**
---
**Name**:  _Ali Hamza_
**Github ID**: *ali123606*
**Role**: *frontend developer*
---
https://github.com/user-attachments/assets/1c1c7b72-4006-4472-9082-856d036a346b

make website responsive for small devices

---

public/index.html

---
---
---
---
---
---
---
---
--- …

added chatbot

---

style.css

---
---
---
---
---
---
---
---
--- …

updated css styles

---

index.html
style.css
styles.css

---
---
---
---
---
---
---
---
--- …

update footer section

---

src/App.css
style.css

---
---
---
---
---
---
---
---
--- …

added more styles

---

src/components/Feedback/Feedbacksection.js

---
---
---
---
---
---
---
---
--- …

Added new features in feedback form for the better response

---

src/components/Feedback/Feedbacksection.css
src/components/Feedback/Feedbacksection.js

---
---
---
---
---
---
---
---
--- …

Improve the styling of the feedback form with dynamic ui

---

src/App.css
src/components/Feedback/Feedbacksection.css

---
---
---
---
---
---
---
---
--- …

Make the whole website responsive for the both android and windows Devices and add more stylings

---

src/App.js
src/components/Disclaimer/Disclaimer.css
src/components/Disclaimer/Disclaimer.js
src/components/Feedback/Feedbacksection.css
src/components/Feedback/Feedbacksection.js
src/components/Footer.jsx

- Added a new **Disclaimer Page** (`Disclaimer.jsx`, `Disclaimer.css`)
- Applied a modern **light theme with hover tilt effect**
- Linked the page in the **Footer under Policies section**
- Ensured component responsiveness
Fixes : #892 
- I noticed a runtime error in the **RealTimeMarketData** component due to null access. Didn’t fix it here as it’s out of scope for this PR — but happy to address in a separate one if needed
First SS in dark theme mode and Second one is in light theme mode

Added Disclaimer Page
